# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: check-readme

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-readme:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: "release" }
          #- { os: ubuntu-latest, r: "devel" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: r-lib/actions/setup-pandoc@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        with:
          pandoc-version: "latest"

      - uses: r-lib/actions/setup-r@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        with:
          cache-version: 2
          needs: check
          extra-packages: |
            local::.
            any::insight
            any::datawizard
            any::parameters
            any::performance
            any::bayestestR
            any::effectsize
            any::correlation
            any::report
            any::see
            any::modelbased

      - name: Render README
        run: |
          options(
            crayon.enabled = TRUE,
            warn = 2L
          )
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}
