# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: check-vignette-warnings

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-vignette-warnings:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "latest"

      - uses: r-lib/actions/setup-r@v2
        with:
          #r-version: "devel"
          use-public-rspm: true

      - name: Install packages from source
        run: |
          if (getRversion() < "4.4.0") {
            # later versions of Matrix require R >= 4.4
            install.packages(
              "https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.6-5.tar.gz",
              repos = NULL,
              type = "source"
            )
          }
          install.packages(c("TMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          upgrade: "TRUE"
          cache-version: 2
          extra-packages: |
            ivprobit=?ignore-before-r=100.0.0
            mhurdle=?ignore-before-r=100.0.0
            lme4=?ignore-before-r=100.0.0
            mmrm=?ignore-before-r=100.0.0
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            MatrixModels=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
            any::BH
            any::purrr
            local::.
          pak-version: devel

      # install *after* other deps to avoid FreeADFunObject error
      - name: Install other packages from source
        run: |
          install.packages(c("mmrm", "MatrixModels", "glmmTMB", "lme4"), type = "source")
        shell: Rscript {0}

      - name: Build vignettes
        run: |
          options(crayon.enabled = TRUE, warn = 2L)
          vignettes <- fs::dir_ls("vignettes/", glob = "*.Rmd", recurse = TRUE)
          purrr::walk(vignettes, ~rmarkdown::render(.x))
        shell: Rscript {0}
