# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: check-styling

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Air
        uses: posit-dev/setup-air@cf390573ff4fe0f198f35df3a642b1409328d859 # v1

      - name: Run air format
        run: air format --check .
