# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: check-test-warnings

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-test-warnings:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          #r-version: "devel"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          upgrade: "TRUE"
          cache-version: 2
          extra-packages: |
            any::devtools
            ivprobit=?ignore-before-r=100.0.0
            mhurdle=?ignore-before-r=100.0.0
            local::.
          pak-version: devel

      - name: Run Tests
        run: |
            options(crayon.enabled = TRUE)
            pkgload::load_all()
            test_script_paths <- testthat::find_test_scripts("tests/testthat")
            test_with_warning_as_error <- function(path) {
              withr::local_options(list(warn = 2L))
              testthat::test_file(path, stop_on_failure = TRUE, stop_on_warning = TRUE)
            }
            purrr::walk(test_script_paths, test_with_warning_as_error)
        shell: Rscript {0}
