# running testthat with options(warn = 2) to fail on test warnings
on:
  workflow_call:

#name: check-test-warnings

jobs:
  check-test-warnings:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "devel"
          use-public-rspm: true

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            local::.

      - name: Run Tests
        run: |
          options(crayon.enabled = TRUE, warn = 2L)
          if (Sys.getenv("_R_CHECK_FORCE_SUGGESTS_", "") == "") {
            Sys.setenv("_R_CHECK_FORCE_SUGGESTS_" = "false")
          }
          testthat::test_dir("tests")
        shell: Rscript {0}
