# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: check-spelling

on:
  workflow_call:

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "latest"

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Spell check
        run: |
          install.packages(c("spelling", "cli"))
          options(crayon.enabled = TRUE)
          spelling_mistakes <- spelling::spell_check_package()
          cli::cli_rule()
          if (length(spelling_mistakes$word) > 0L) {
            print(spelling_mistakes)
            cli::cli_abort("Spelling errors found. Either correct them or update `inst/WORDLIST` using `spelling::update_wordlist()`.")
          } else {
            cli::cli_alert_success("No spelling errors found.")
          }
          cli::cli_rule()
        shell: Rscript {0}
