on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: format_check

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format-15

      - name: Run ClangFormat
        run: make format clang_format=clang-format-15

      - name: Check for a non-empty diff
        run: git diff-files -U --exit-code
