# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: HTML5 check

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  HTML5-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      #_R_CHECK_RD_VALIDATE_RD2HTML_: true

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          #r-version: "devel"
          http-user-agent: "release"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            any::rcmdcheck
            any::V8
          dependencies: "character()"

      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Install tidy
        run: sudo apt install tidy

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--as-cran", "--no-codoc", "--no-examples", "--no-tests", "--no-vignettes", "--no-build-vignettes", "--ignore-vignettes", "--no-install")'
          build_args: 'c("--no-build-vignettes")'
          error-on: '"note"'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_RD_XREFS_: false
