# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_call:

#name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            r-lib/lintr
            local::.
          needs: lint

      - name: Lint
        run: |
          options(crayon.enabled = TRUE)
          library(lintr)
          lint_package(linters = linters_with_defaults(
            absolute_path_linter = NULL,
            commented_code_linter = NULL,
            cyclocomp_linter = cyclocomp_linter(40),
            extraction_operator_linter = NULL,
            implicit_integer_linter = NULL,
            line_length_linter(120),
            namespace_linter = NULL,
            nonportable_path_linter = NULL,
            object_name_linter = NULL,
            object_length_linter(50),
            object_usage_linter = NULL,
            todo_comment_linter = NULL,
            undesirable_function_linter(c("mapply" = NA, "sapply" = NA, "setwd" = NA)),
            undesirable_operator_linter = NULL,
            unnecessary_concatenation_linter(allow_single_expression = FALSE),
            unused_import_linter = NULL,
            defaults = linters_with_tags(tags = NULL)
          ))
        shell: Rscript {0}
