# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: lint

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2
        with:
          cache-version: 2
          extra-packages: |
            r-lib/lintr
            local::.
          needs: lint

      - name: Lint
        run: |
          options(crayon.enabled = TRUE)
          library(lintr)
          # Air takes care of all formatting
          lint_package(linters = all_linters(
            absolute_path_linter = NULL,
            brace_linter = NULL,
            commas_linter = NULL,
            coalesce_linter = NULL,
            commented_code_linter = NULL,
            cyclocomp_linter(40L),
            commas_linter = NULL,
            function_left_parenthesis_linter = NULL,
            if_not_else_linter(exceptions = character(0L)),
            indentation_linter = NULL,
            infix_spaces_linter = NULL,
            implicit_integer_linter = NULL,
            library_call_linter = NULL,
            line_length_linter = NULL,
            paren_body_linter = NULL,
            namespace_linter = NULL,
            nonportable_path_linter = NULL,
            object_length_linter(50L),
            object_name_linter = NULL,
            object_usage_linter = NULL,
            one_call_pipe_linter = NULL,
            semicolon_linter = NULL,
            spaces_inside_linter = NULL,
            spaces_left_parentheses_linter = NULL,
            todo_comment_linter = NULL,
            trailing_blank_lines_linter = NULL,
            trailing_whitespace_linter = NULL,
            undesirable_function_linter(c("mapply" = NA, "setwd" = NA)),
            undesirable_operator_linter = NULL,
            unnecessary_concatenation_linter(allow_single_expression = FALSE),
            unused_import_linter = NULL,
            whitespace_linter = NULL
          ))
        shell: Rscript {0}
