# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: lint

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          upgrade: "TRUE"
          cache-version: 2
          pak-version: devel
          extra-packages: |
            r-lib/lintr
            local::.
          needs: lint

      - name: Lint
        run: |
          options(crayon.enabled = TRUE)
          library(lintr)
          lint_package(linters = all_linters(
            coalesce_linter = NULL,
            absolute_path_linter = NULL,
            cyclocomp_linter(40L),
            if_not_else_linter(exceptions = character(0L)),
            indentation_linter = NULL,
            implicit_integer_linter = NULL,
            library_call_linter = NULL,
            line_length_linter(120L),
            namespace_linter = NULL,
            nonportable_path_linter = NULL,
            object_length_linter(50L),
            object_name_linter = NULL,
            object_usage_linter = NULL,
            one_call_pipe_linter = NULL,
            todo_comment_linter = NULL,
            commented_code_linter = NULL,
            undesirable_function_linter(c("mapply" = NA, "setwd" = NA)),
            undesirable_operator_linter = NULL,
            unnecessary_concatenation_linter(allow_single_expression = FALSE),
            unused_import_linter = NULL
          ))
        shell: Rscript {0}
