# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: lint-changed-files

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint-changed-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          upgrade: "TRUE"
          cache-version: 2
          extra-packages: |
            any::gh
            any::purrr
            r-lib/lintr
          needs: check

      - name: Install package
        run: R CMD INSTALL .

      - name: Extract and lint files changed by this PR
        run: |
          options(crayon.enabled = TRUE)
          files <- gh::gh("GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")
          changed_files <- purrr::map_chr(files, "filename")
          all_files <- list.files(recursive = TRUE)
          exclusions_list <- as.list(setdiff(all_files, changed_files))
          library(lintr)
          options(crayon.enabled = TRUE)
          library(lintr)
          lint_package(linters = all_linters(
            absolute_path_linter = NULL,
            cyclocomp_linter(40L),
            if_not_else_linter(exceptions = character(0L)),
            indentation_linter = NULL,
            implicit_integer_linter = NULL,
            library_call_linter = NULL,
            line_length_linter(120L),
            namespace_linter = NULL,
            nonportable_path_linter = NULL,
            object_length_linter(50L),
            object_name_linter = NULL,
            object_usage_linter = NULL,
            todo_comment_linter = NULL,
            commented_code_linter = NULL,
            undesirable_function_linter(c("mapply" = NA, "setwd" = NA)),
            undesirable_operator_linter = NULL,
            unnecessary_concatenation_linter(allow_single_expression = FALSE),
            unused_import_linter = NULL
          ), exclusions = exclusions_list)
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
