# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

#name: pkgdown

on:
  workflow_call:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1.11"

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: 'TRUE'
          cache-version: 2
          extra-packages: |
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            MatrixModels=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
            r-lib/pkgdown
            local::.
          needs: website

      # install *after* other deps to avoid FreeADFunObject error
      - name: Install other packages from source
        run: |
          install.packages(c("mmrm", "MatrixModels", "glmmTMB", "lme4"), type = "source")
        shell: Rscript {0}

      - name: Build site
        run: |
          options(crayon.enabled = TRUE)
          pkgdown::build_site_github_pages(run_dont_run = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: docs
