# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: R-CMD-check-devel-easystats

on:
  workflow_call:

jobs:
  R-CMD-check-devel-easystats:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1.9"

      - uses: r-lib/actions/setup-r@v2
        with:
          #r-version: "devel"
          http-user-agent: "release"
          use-public-rspm: true

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: 'TRUE'
          cache-version: 2
          extra-packages: |
            local::.
            any::rcmdcheck
            any::BH
            easystats/insight
            easystats/datawizard
            easystats/parameters
            easystats/performance
            easystats/bayestestR
            easystats/effectsize
            easystats/correlation
            easystats/modelbased
            mmrm=?ignore-before-r=100.0.0
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            MatrixModels=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
          needs: check

      # install *after* other deps to avoid FreeADFunObject error
      - name: Install mmrm and glmmTMB from source
        run: |
          install.packages(c("mmrm", "MatrixModels", "glmmTMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: '"note"'
