# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: R-CMD-check

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) ${{ matrix.config.locale }}

    strategy:
      fail-fast: false
      matrix:
        config:
          #- {os: macOS-latest, r: 'devel'}
          - { os: macOS-latest, r: "release" }
          #- { os: macOS-latest, r: "oldrel" }
          #- {os: macOS-latest, r: 'oldrel-2'}
          #- {os: macOS-latest, r: 'oldrel-3'}

          #- { os: windows-latest, r: "next" }
          - { os: windows-latest, r: "devel" }
          - { os: windows-latest, r: "release" }
          - { os: windows-latest, r: "oldrel" }
          #- {os: windows-latest, r: 'oldrel-2'}
          #- {os: windows-latest, r: 'oldrel-3'}

          # Use 3.6 to trigger usage of RTools35
          #- { os: windows-latest, r: "3.6" }
          # use 4.1 to check with rtools40's older compiler
          #- { os: windows-latest, r: "4.1" }

          #- { os: ubuntu-latest, r: "next" }
          - { os: ubuntu-latest, r: "devel" }
          #- { os: ubuntu-latest, r: "devel", locale: "zh_CN" }
          - { os: ubuntu-latest, r: "release" }
          - { os: ubuntu-latest, r: "oldrel" }
          - { os: ubuntu-latest, r: "oldrel-2" }
          - { os: ubuntu-latest, r: "oldrel-3" }
          - { os: ubuntu-latest, r: "3.6" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # - name: Set locale
      #   if: matrix.config.locale == 'zh_CN.UTF-8'
      #   run: |
      #     sudo locale-gen zh_CN.UTF-8
      #     echo "LC_ALL=zh_CN.UTF-8" >> $GITHUB_ENV

      # - name: Set locale
      #   if: matrix.config.locale == 'en_US'
      #   run: |
      #     sudo locale-gen en_US
      #     echo "LC_ALL=en_US" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "latest"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: "release"
          use-public-rspm: true

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: 'TRUE'
          cache-version: 2
          extra-packages: |
            any::rcmdcheck
            any::BH
            ivprobit=?ignore-before-r=100.0.0
            mhurdle=?ignore-before-r=100.0.0
            BayesFactor=?ignore-before-r=100.0.0
            cplm=?ignore-before-r=100.0.0
            lme4=?ignore-before-r=100.0.0
            mmrm=?ignore-before-r=100.0.0
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            MatrixModels=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
            brms=?ignore-before-r=4.4.0
            estimability=?ignore-before-r=4.3.0
            effects=?ignore-before-r=4.3.0
            nestedLogit=?ignore-before-r=4.3.0
            FactoMineR=?ignore-before-r=4.3.0
            factoextra=?ignore-before-r=4.3.0
            emmeans=?ignore-before-r=4.3.0
            bayesQR=?ignore-before-r=4.2.0
            MuMIn=?ignore-before-r=4.2.0
            ape=?ignore-before-r=4.1.0
            car=?ignore-before-r=4.1.0
            drc=?ignore-before-r=4.1.0
            EGAnet=?ignore-before-r=4.1.0
            ggpubr=?ignore-before-r=4.1.0
            Hmisc=?ignore-before-r=4.1.0
            mediation=?ignore-before-r=4.1.0
            rstatix=?ignore-before-r=4.1.0
            PROreg=?ignore-before-r=4.1.0
            rmcorr=?ignore-before-r=4.1.0
            rms=?ignore-before-r=4.1.0
            randomForest=?ignore-before-r=4.1.0
            pbkrtest=?ignore-before-r=4.1.0
            afex=?ignore-before-r=4.1.0
            car=?ignore-before-r=4.1.0
            ivreg=?ignore-before-r=4.1.0
            AER=?ignore-before-r=4.1.0
            WRS2=?ignore-before-r=4.1.0
            tinytable=?ignore-before-r=4.1.0
            epiR=?ignore-before-r=4.0.0
            energy=?ignore-before-r=4.0.0
            gam=?ignore-before-r=4.0.0
            gdtools=?ignore-before-r=4.0.0
            gsl=?ignore-before-r=4.0.0
            fastICA=?ignore-before-r=4.0.0
            metafor=?ignore-before-r=4.0.0
            metadat=?ignore-before-r=4.0.0
            metaplus=?ignore-before-r=4.0.0
            multgee=?ignore-before-r=4.0.0
            panelr=?ignore-before-r=4.0.0
            jtools=?ignore-before-r=4.0.0
            mmrm=?ignore-before-r=4.0.0
            rsvd=?ignore-before-r=4.0.0
            sparsepca=?ignore-before-r=4.0.0
            qqconf=?ignore-before-r=4.0.0
            qqplotr=?ignore-before-r=4.0.0
            rtdists=?ignore-before-r=4.0.0
            VGAM=?ignore-before-r=4.0.0
            ggside=?ignore-before-r=4.0.0
          needs: check

      # install *after* other deps to avoid FreeADFunObject error
      # glmmTMB uses `deparse1()`, which was introduced in R 4.0
      - name: Install other packages from source
        run: |
          install.packages(
            c("BayesFactor", "cplm", "mmrm", "MatrixModels", "glmmTMB", "lme4"),
            type = "source"
          )
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: 'ifelse(getRversion() > "4.3", "note", "warning")'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_FORCE_SUGGESTS_: false
          _R_CHECK_STOP_ON_INVALID_NUMERIC_VERSION_INPUTS_: true
