# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# R CMD Check will fail on NOTE.

on:
  workflow_call:

# name: R-CMD-check-strict

jobs:
  R-CMD-check-strict:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # CRAN does not provide macOS binaries for R-devel, so some packages
          # need to be built from source. To avoid that, use R-release.
          - { os: macos-latest, r: "release" }
          - { os: windows-latest, r: "devel" }
          - { os: ubuntu-latest, r: "devel" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.0"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: "release"
          use-public-rspm: true

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      # TODO: Check which of the ignore conditions are still relevant given the
      # current suggested dependencies and the minimum supported R version.
      # Update if anything out of date or not needed anymore.
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            any::rcmdcheck
            any::BH
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
            epiR=?ignore-before-r=4.0.0
            gam=?ignore-before-r=4.0.0
            gdtools=?ignore-before-r=4.0.0
            fastICA=?ignore-before-r=4.0.0
            metafor=?ignore-before-r=4.0.0
            panelr=?ignore-before-r=4.0.0
            jtools=?ignore-before-r=4.0.0
            mmrm=?ignore-before-r=4.0.0
            rsvd=?ignore-before-r=4.0.0
            sparsepca=?ignore-before-r=4.0.0
            FactoMineR=?ignore-before-r=4.1.0
            factoextra=?ignore-before-r=4.1.0
            emmeans=?ignore-before-r=4.1.0
            rmcorr=?ignore-before-r=4.1.0
            randomForest=?ignore-before-r=4.1.0
            MuMIn=?ignore-before-r=4.2.0
            pbkrtest=?ignore-before-r=4.1.0
            afex=?ignore-before-r=4.1.0
            car=?ignore-before-r=4.1.0
            ivreg=?ignore-before-r=4.1.0
            AER=?ignore-before-r=4.1.0
          needs: check

      # install *after* other deps to avoid FreeADFunObject error
      - name: Install glmmTMB from source
        run: |
          install.packages("glmmTMB", type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: '"note"'
