# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: R-CMD-check-strict

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check-strict:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # CRAN does not provide macOS binaries for R-devel, so some packages
          # need to be built from source. To avoid that, use R-release on macOS.
          - { os: macos-latest, r: "release", rtools: "42" }
          - { os: windows-latest, r: "devel", rtools: "43" }
          - { os: ubuntu-latest, r: "devel", rtools: "43" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1.6"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: "release"
          use-public-rspm: true
          rtools-version: ${{ matrix.config.rtools }}

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ##                              IMPORTANT                                       ##
      ##                                                                              ##
      ##             Strict checks are run only on R-release and R-devel.             ##
      ##  No deps are ignored since all deps ought to be available on these versions  ##
      ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: '"TRUE"'
          extra-packages: |
            any::rcmdcheck
            any::BH
            mmrm=?ignore-before-r=100.0.0
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
            cplm=?ignore
            panelr=?ignore
            speedglm=?ignore
          needs: check

      # install *after* other deps to avoid FreeADFunObject error
      - name: Install mmrm and glmmTMB from source
        run: |
          install.packages(c("mmrm", "glmmTMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: '"note"'
