# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: R-CMD-check-devel-easystats

on:
  workflow_call:

jobs:
  R-CMD-check-devel-easystats:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "latest"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "devel"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: "TRUE"
          cache-version: 2
          extra-packages: |
            local::.
            any::rcmdcheck
            any::BH
            easystats/insight
            easystats/datawizard
            easystats/parameters
            easystats/performance
            easystats/bayestestR
            easystats/effectsize
            easystats/correlation
            easystats/modelbased
            ivprobit=?ignore-before-r=100.0.0
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: 'ifelse(getRversion() > "4.3", "note", "warning")'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_FORCE_SUGGESTS_: false
          _R_CHECK_STOP_ON_INVALID_NUMERIC_VERSION_INPUTS_: true
