on:
  workflow_call:

#name: R-CMD-check-devel-easystats

jobs:
  R-CMD-check-devel-easystats:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.0"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "devel"
          http-user-agent: "release"
          use-public-rspm: true

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ##                              IMPORTANT                                       ##
      ##                                                                              ##
      ##             Strict checks are run only on R-release and R-devel.             ##
      ##  No deps are ignored since all deps ought to be available on these versions  ##
      ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            local::.
            any::rcmdcheck
            any::BH
            easystats/insight
            easystats/datawizard
            easystats/parameters
            easystats/performance
            easystats/bayestestR
            easystats/effectsize
            easystats/correlation
            easystats/modelbased
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
          needs: check

      # install *after* other deps to avoid FreeADFunObject error
      - name: Install glmmTMB from source
        run: |
          install.packages("glmmTMB", type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: '"note"'
