# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: R-CMD-check

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) ${{ matrix.config.locale }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # CRAN doesn't provide binaries for macOS on R-devel, so skip because
          # it will be too slow otherwise
          #- {os: macOS-latest, r: 'devel'}
          - { os: macOS-latest, r: "release" }

          - { os: windows-latest, r: "devel"   }
          - { os: windows-latest, r: "release" }

          - { os: ubuntu-latest, r: "devel"    }
          - { os: ubuntu-latest, r: "release"  }
          - { os: ubuntu-latest, r: "oldrel-1" }
          - { os: ubuntu-latest, r: "oldrel-2" }
          - { os: ubuntu-latest, r: "oldrel-3" }
          - { os: ubuntu-latest, r: "oldrel-4" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "latest"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: "TRUE"
          extra-packages: |
            any::rcmdcheck
            any::BH
            any::RcppEigen
            ivprobit=?ignore-before-r=100.0.0
            rms=?ignore-before-r=4.4.0
            brms=?ignore-before-r=4.3.0
            cgam=?ignore-before-r=4.4.0
            robustlmm=?ignore-before-r=4.4.0
            multgee=?ignore-before-r=4.1.0
            VGAM=?ignore-before-r=4.1.0
            plm=?ignore-before-r=4.1.0
            WeightIt=?ignore-before-r=4.1.0
            effects=?ignore-before-r=4.3.0
            nestedLogit=?ignore-before-r=4.3.0
            FactoMineR=?ignore-before-r=4.3.0
            factoextra=?ignore-before-r=4.3.0
            bayesQR=?ignore-before-r=4.2.0
            MuMIn=?ignore-before-r=4.4.0
            distributional=?ignore-before-r=4.2.0
            Hmisc=?ignore-before-r=4.2.0
            mediation=?ignore-before-r=4.2.0
            pbkrtest=?ignore-before-r=4.2.0
            serp=?ignore-before-r=4.1.0
            VGAM=?ignore-before-r=4.1.0
            censReg=?ignore-before-r=4.1.0
            BayesFactor=?ignore-before-r=4.4.0
            MatrixModels=?ignore-before-r=4.4.0
            glmmTMB=?ignore-before-r=4.1.0
            collapse=?ignore-before-r=4.1.0
            estimability=?ignore-before-r=4.1.0
            emmeans=?ignore-before-r=4.1.0
            feisr=?ignore-before-r=4.1.0
            quantreg=?ignore-before-r=4.4.0
            ape=?ignore-before-r=4.1.0
            drc=?ignore-before-r=4.1.0
            EGAnet=?ignore-before-r=4.1.0
            ggpubr=?ignore-before-r=4.1.0
            rstatix=?ignore-before-r=4.1.0
            PROreg=?ignore-before-r=4.2.0
            rmcorr=?ignore-before-r=4.1.0
            randomForest=?ignore-before-r=4.1.0
            lavaan=?ignore-before-r=4.1.0
            afex=?ignore-before-r=4.2.0
            car=?ignore-before-r=4.4.0
            ICSOutlier=?ignore-before-r=4.1.0
            ICS=?ignore-before-r=4.1.0
            ivreg=?ignore-before-r=4.2.0
            AER=?ignore-before-r=4.2.0
            WRS2=?ignore-before-r=4.1.0
            osqp=?ignore-before-r=4.4.0
            CVXR=?ignore-before-r=4.4.0
            fungible=?ignore-before-r=4.4.0
            Brobdingnag=?ignore-before-r=4.4.0
            bridgesampling=?ignore-before-r=4.4.0
            metaBMA=?ignore-before-r=4.4.0
            tinytable=?ignore-before-r=4.1.0
            srvyr=?ignore-before-r=4.1.0
            survey=?ignore-before-r=4.1.0
            correlation=?ignore-before-r=4.1.0
            svylme=?ignore-before-r=4.1.0
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: 'ifelse(getRversion() > "4.3", "note", "warning")'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_FORCE_SUGGESTS_: false
          _R_CHECK_STOP_ON_INVALID_NUMERIC_VERSION_INPUTS_: true
