# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: revdepcheck

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  revdepcheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    if: startsWith(github.head_ref, 'rc')

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "latest"

      - uses: r-lib/actions/setup-r@v2

      - name: Install packages from source
        run: |
          if (getRversion() < "4.4.0") {
            # later versions of Matrix require R >= 4.4
            install.packages(
              "https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.6-5.tar.gz",
              repos = NULL,
              type = "source"
            )
          }
          install.packages(c("TMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          upgrade: 'TRUE'
          cache-version: 2
          extra-packages: |
            r-lib/revdepcheck
            local::.
            any::rcmdcheck
            any::BH
            ivprobit=?ignore-before-r=100.0.0
            mhurdle=?ignore-before-r=100.0.0
            lme4=?ignore-before-r=100.0.0
            mmrm=?ignore-before-r=100.0.0
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            MatrixModels=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
          pak-version: devel

      # install *after* other deps to avoid FreeADFunObject error
      - name: Install other packages from source
        run: |
          install.packages(c("mmrm", "MatrixModels", "glmmTMB", "lme4"), type = "source")
        shell: Rscript {0}

      - name: Revdepcheck
        run: |
          options(crayon.enabled = TRUE)
          library(revdepcheck)
          revdep_check(num_workers = 4)
          revdep_report()
          revdep_reset()
        shell: Rscript {0}

      #- uses: stefanzweifel/git-auto-commit-action@v4
