# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: test-coverage

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1.8"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "devel"
          http-user-agent: "release"
          use-public-rspm: true
          rtools-version: "43"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: '"TRUE"'
          extra-packages: |
           any::covr
          needs: coverage

      - name: Test coverage
        run: |
          options(crayon.enabled = TRUE)
          covr::codecov(quiet = FALSE)
        shell: Rscript {0}
