# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: test-coverage

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1.8"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          use-public-rspm: true

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            any::covr
            mmrm=?ignore-before-r=100.0.0
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
            local::.
          needs: coverage

      - name: Install mmrm and glmmTMB from source
        run: |
          install.packages(c("mmrm", "glmmTMB"), type = "source")
        shell: Rscript {0}

      - name: Test coverage
        run: |
          options(crayon.enabled = TRUE)
          covr::codecov(quiet = FALSE)
        shell: Rscript {0}
