# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

# name: test-coverage-examples

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-coverage-examples:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: r-lib/actions/setup-pandoc@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        with:
          pandoc-version: "latest"

      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        with:
          cache-version: 2
          extra-packages: |
            any::covr
            local::.
          needs: coverage

      - name: Test example coverage
        run: |
          options(crayon.enabled = TRUE)
          library(covr)
          coverage <- covr::package_coverage(
            type = c("examples", "vignettes"),
            quiet = TRUE,
            commentDonttest = FALSE,
            commentDontrun = FALSE
          )
          print(coverage)
          percent_coverage <- covr::percent_coverage(coverage)
          threshold <- 50
          cli::cli_rule()
          if (percent_coverage < threshold) {
            cli::cli_abort("Code coverage using examples is below the required threshold ({threshold}%).")
          } else {
            cli::cli_alert_success("Code coverage using examples is above the required threshold ({threshold}%).")
          }
          cli::cli_rule()
        shell: Rscript {0}
