# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/

#name: update-to-latest-easystats

on:
  workflow_call:

jobs:
  update-to-latest-easystats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          extra-packages: |
            any::usethis

      - name: Update DESCRIPTION file
        id: update_description
        run: |
          usethis::use_latest_dependencies()
        shell: Rscript {0}

      - name: Bump package version
        id: bump_version
        if: ${{ steps.update_description.outputs.changed }}
        run: |
          usethis::use_version("dev", push = FALSE)
        shell: Rscript {0}

      - name: Check for changes in DESCRIPTION
        id: check_description
        run: |
          git status
          git add --all

      - name: Create pull request
        #if: ${{ steps.update_description.outputs.changed }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: desc-${{ github.ref_name }}-${{ github.job }}
          branch-suffix: timestamp
          delete-branch: true
          title: "Update `DESCRIPTION` to use latest 'easystats' dependencies"
          body: "Automatically updated the `DESCRIPTION` file using `usethis::use_latest_dependencies()`."
          labels: "auto-update"
          add-paths: |
            DESCRIPTION
